### ISSUE TITLE
Mock DB with file read & write

### ISSUE THREAD

**Issue by ekrembal** [chainwayxyz/clementine#128]
### Issue Description

We need to modify databases so that they read from a file, and every time an update function is called, they should read from the file, deserialize the structure, update it, serialize it again, and write it back to the file. Additionally, making the database functions asynchronous (while maintaining synchronous code internally) will be beneficial for actual database scenarios.

### Tasks

Parts of the task:
- [ ] Make DB struct Serializable
- [ ] Write read and write logic
- [ ] Change DB functions

### Deadline of the Issue

24 April
