### ISSUE TITLE
DB functions: Update return values and make them async

### ISSUE THREAD

**Issue by ceyhunsen** [chainwayxyz/clementine#132]
### Issue Description

DB functions currently does not returns any kind of error, if database is not ready or not have requested information. They should return a `Result` type for error checking. This will be useful in the future, when a real DBMS is replaced with mock DB.

Also, DB functions should use tokio's `async` feature.

### Tasks

Parts of the task:

- [x] Convert DB function's return type to `Result`
- [x] Refactor other parts of the code to handle the new `Result` return type
- [x] Add `async` functionality to DB functions
- [x] Add new tests if needed for the new `async` functionality

### Deadline of the Issue

26.04.2024

**Comment by ceyhunsen** [comment]
This issue can't be completed in one PR. Because there are some ongoing changes in dev branch and adding async support has a high chance of conflicting with that branch. It is better to wait dev branch to be merged to main for adding async support.
