### ISSUE TITLE
Testnet Tracking Issue

### ISSUE THREAD

**Issue by ekrembal** [chainwayxyz/clementine#134]
### Issue Description

We are very close to making our testnet targets.

### Tasks

- [x] Sync dev branch with main branch
- [x] Decide on args parsing method
- [x] Move every constants to the args file
- [x] Tests for move_tx sending
- [x] Implement new_withdrawal endpoint
- [x] Tests for withdrawal tx sending
- [x] new_deposit and new_withdrawal should write the request to the db and a task should fetch the requests and act on it
- [x] Tests on regtest and database
- [ ] Musig2

### Deadline of the Issue

May 2024
