### ISSUE TITLE
Testnet Tracking Issue

### ISSUE THREAD

**Issue by ekrembal** [chainwayxyz/clementine#183]
### Proposal Description

- [ ] Bitcoin Mock RPC ready to integrate
- [x] Risc0 FFLONK Prover
    - [x] Custom stark-to-snark circuit that outputs journal only.
    - [ ] Output the blake3 hash of the journal only (benchmark needed in bitvm between blake3 and scalarmul)
    - [ ] Faster FFLONK prover
- [ ] BitVM FFLONK Verifier
    - [x] Verify arbitrary fflonk proofs with single script
    - [ ] Splitting fflonk scripts
- [ ] TX Graph
    - [x] Design the graph
    - [ ] Implement BitVM Setup script
        - [ ]  FFLONK Verification key -> subscript, verifier challenge utxo
        - [ ] N-of-N Signed burn transactions.
    - [ ] Design how to store preimages for operator commit tx.
- [ ] Lightclient Circuit: Verify batch proofs
- [ ] Bridge Circuit
    - [ ] Verify Lightclient proof
    - [ ] Extract withdrawal addresses from the L2 State root
    - [ ] SPV Proof for front covered withdrawals
    - [ ] Operator commit to take check
    - [ ] Continuation from previous period's bridge proof. (This can be done in 2 ways, either recursive proving or continuations.)
    - [ ] Verify verifier's challenge proof (groth16 proof)
    - [x] Longest chain to decide winner.
- [ ] CPFP Fee bumber.
