### ISSUE TITLE
BitVM Tracking Issue

### ISSUE THREAD

**Issue by ekrembal** [chainwayxyz/clementine#203]
## Current status:
number of pieces: ~~10359~~ 1374 scripts
script total size: ~~5115859126~~ 4.400.835.584 bytes
max (script size): ~~3422794 bytes (1.5M except one outlier that is 3.5M)~~ 3.883.637 bytes
max (max stack size): ~~958 items~~ 942 items

~~30553~~ 10044 intermediate value, (254 bit commitment, others are Fq or Fr, we can think of them as Fq)
one Fq checksig is ~~9522~~ 41156 bytes

We can fit ~~12~~ 26 Fq in 26*36<1000 stack elements

## Goal:

number of subscripts: ~500
assert tx size: ~4mb

## Things to improve:
- [x] Try different D instead of D=16 in Winternitz
- [x] Switch to groth16-affine
- [x] Merge optimizations and our split work in a single branch (dev branch)
- [x] What is the maximum number of Fq we can get with hash then commit, Result: negative, since blake3 is 75k.
- [x] G1.scalar_mul optimization
- [x] Fq.tmul bug fixes
- [x] Integrate tmul into groth16 verifier script
- [x] fq2 mul by using 2 multiplications with 2 linear combinations

## Backlog

- [ ] fq mul_by_constant and square methods
- [ ] quad miller loop optimization with window method
- [ ] Test optimizations in FFLONK 

## TODO:

- [ ] Hashing a fq12 with blake3, Hash64(Hash128(Hash64 | Hash64 | Hash64 | Hash64) | Hash128)
 (@just-erray, deadline: 01/10/2024)
- [ ] Verifying the output hash of fq12 with Winternitz signature. (@just-erray, deadline: 02/10/2024 )

**Comment by ekrembal** [comment]
Let's close this in favor of issues on BitVM repo
