### ISSUE TITLE
Fix deposit_address test

### ISSUE THREAD

**Issue by ozankaymak** [chainwayxyz/clementine#217]
### Issue Description

After switching to use MuSig2, surely this deposit address test is broken:
https://github.com/chainwayxyz/clementine/blob/71085e878eb974a4d378295f77c67eb2651f70ef/core/src/transaction_builder.rs#L521
Needs fixing.
Update: Also user_deposit binary needs fixing as well.

### Tasks

Parts of the task:
- [ ] Find the resulting XOnlyPublicKey after aggregating the keys.
- [ ] Obtain the deposit_address using some other library.
- [ ] Fix the test address.
- [ ] Fix user_deposit binary.

### Deadline of the Issue

Aug 16, Friday

**Comment by ozankaymak** [comment]
Closed by #278 .
