### ISSUE TITLE
Test for deposit flow

### ISSUE THREAD

**Issue by ekrembal** [chainwayxyz/clementine#223]
### Issue Description

Write test for a single deposit flow

### Tasks

Parts of the task:
- [ ] Create a user, opeators and verifiers
- [ ] User will make a deposit
- [ ] The test will call new_deposit rpc endpoints for operators and verifiers
- [ ] Aggrete the pubNonces
- [ ] Call the operator_kickoffs_generated_rpc
- [ ] Call the burn_txs_signed_rpc
- [ ] Call the operator_take_txs_signed_rpc
- [ ] Aggregate the move_commit and move_reveal 
- [ ] Send move_commit and move_reveal txs

### Deadline of the Issue

-

**Comment by ozankaymak** [comment]
Closed
