### ISSUE TITLE
Implement aggreagte partial sigs helper functions

### ISSUE THREAD

**Issue by ekrembal** [chainwayxyz/clementine#233]
### Issue Description

We need to calculate sigHash and Tweak to aggregate partial sigs.
Implement util functions that calculates sighashes from deposit_outpoints, then aggreagtes the partial sigs. This function will be called from the backend itself and from flow tests

### Tasks

Parts of the task:
- [ ] Impl aggreagte operator take partial sigs
- [ ] Impl aggreagte operator slash or take partial sigs
- [ ] Impl aggreagte move partial sigs

### Deadline of the Issue

Monday
