### ISSUE TITLE
CI/CD improvements

### ISSUE THREAD

**Issue by ceyhunsen** [chainwayxyz/clementine#242]
### Issue Description

There are some small improvements that needs to be done in CI/CD side of things.

### Tasks

Parts of the task:

- [ ] Pass `--all-targets` flag to Clippy: `cargo clippy --all-targets`
- [ ] Separation of compiling, testing on Bitcoin regtest and testing on mock RPC task
- [ ] Separate debug and release configured builds and tests

### Deadline of the Issue

2024
