### ISSUE TITLE
Get rid of clementine-circuits in dependency for core

### ISSUE THREAD

**Issue by ekrembal** [chainwayxyz/clementine#261]
### Issue Description

We should not use clementine-circuits/constants instead we should get BRIDGE_AMOUNT from config.toml

### Tasks

Parts of the task:
- [ ] Move constants BRIDGE_AMOUNT, DEPOSIT_USER_TAKES_AFTER, OPERATOR_TAKES_AFTER
- [ ] Move sha256_hash
- [ ] Disable env_writer.rs, mock/env.rs and merkle.rs
- [ ] remove clementine-circuits from dependency
- [ ] Don't compile clementine-circuits and risc0-guests
- [ ] Also get rid of risc0-zkvm and sha accelerators

### Deadline of the Issue

Friday
