### ISSUE TITLE
Implement winternitz derivation

### ISSUE THREAD

**Issue by ekrembal** [chainwayxyz/clementine#334]
### Issue Description

We need a way to sign and generate winternitz signatures

### Tasks

Parts of the task:
- [x] research derivation paths
- [x] implement generating winternitz pubkeys in actor.rs
- [x] implement signing winternitz signatures in actor.rs

### Deadline of the Issue
25/10/2024
