### ISSUE TITLE
Implement Verifier Nonce Gen

### ISSUE THREAD

**Issue by ekrembal** [chainwayxyz/clementine#343]
### Issue Description

We should store secret nonces in memory. 

```
#[derive(Debug)]
pub struct NonceSession {
    pub private_key: secp256k1::SecretKey,
    pub nonces: Vec<(MuSigSecNonce, MuSigPubNonce)>,
}

#[derive(Debug)]
pub struct AllSessions {
    pub cur_id: u32,
    pub sessions: HashMap<u32, NonceSession>,
}
```

Add this to verifiers
```
    pub(crate) nonces:  Arc<Mutex<AllSessions>>
```

can be updated with
```
        let x = self.nonces;
        let mut y=  x.lock().await;
        let mut z = &mut *y;

        z.sessions.insert(z.cur_id, session);
        z.cur_id = z.cur_id + 1;
```

### Tasks

Parts of the task:
- [ ] Research: do we really need to store pubNonces
- [ ] Add timestamp for nonce sessions
- [ ] Delete nonce sessions older than 1 day when nonce_gen is called
- [ ] generate secNonce pubNonce pairs
- [ ] create a session with new private key
- [ ] sign the public key with old private key
- [ ] return the stream

### Deadline of the Issue

25/10/2024

**Comment by ceyhunsen** [comment]
Closed with #359
