### ISSUE TITLE
Implement Verifier Deposit Sign

### ISSUE THREAD

**Issue by ekrembal** [chainwayxyz/clementine#344]
### Issue Description

n-of-n signing of every required signatures

### Tasks

Parts of the task:
- [x] Get the first streamed value
- [x] Check if deposit it correct deposit. (i am not sure we really need to do this)
- [ ] calculate new N-of-N aggregated public key
- [ ] for every operator
  - [ ] calculate kickoff txids
  - [ ] for every kickoff txid
    - [ ] calculate watchtower challenge tx handler and export sighashes
    - [ ] calculate operator assert empty tx handler and export sighashes
    - [ ] calculate operator assert timeout tx handler and export sighashes
    - [ ] calculate disprove tx handler and export sighashes
    - [ ] calculate reimburse tx handler and export the sighash
    - [ ] calculate happy reimburse tx handler and export the sighashes
    - [ ] sign sighashes in parallel
    - [ ] stream the partial signatures

### Deadline of the Issue

8/11/2024

**Comment by ekrembal** [comment]
Done except the sighash stream
