### ISSUE TITLE
Implement Verifier Deposit Finalize

### ISSUE THREAD

**Issue by ekrembal** [chainwayxyz/clementine#354]
### Issue Description

Really similiar to #344 but instead of signing, it will verify aggreagted signatures
We should consider caching calculated sighashes in an array

### Tasks

Parts of the task:
- [x] Do the same as #344 but verify signatures
- [ ] partially sign move tx
- [ ] save final aggregated signatures to the db
- [ ] _Save operator's signatures_ (TODO for future)
- [ ] impelement signature getter to use when needed

### Deadline of the Issue

TBD

**Comment by ekrembal** [comment]
For now let's skip the part with Happy reimburse thing,

this should save the signatures to the table

deposit_outpoint, operator_id, signatures

**Comment by ekrembal** [comment]
Closed with #423
