### ISSUE TITLE
Implement Get Params

### ISSUE THREAD

**Issue by ekrembal** [chainwayxyz/clementine#355]
# Issue Description

Depends on #334 

## Tasks

Parts of the task:
- [ ] Create get params for operator
- [x] Create get params for wathtower
- [ ] Create get patams for verifier

## get_params for watchtower

- [x] Creates Winternitz pubkeys (240 bytes) for every operator and time_tx pair
- [x] Aggregator sends this pubkeys to verifiers
- [x] Verifiers saves these to database

## Deadline of the Issue

1/11/3024
