### ISSUE TITLE
Implement header chain prover

### ISSUE THREAD

**Issue by ekrembal** [chainwayxyz/clementine#356]
### Issue Description

Watchtowers and Operators needs to generate a header chain proof for every new bitcon block and store them in db.

We need one public function, get_header_chain_proof(blocknum)

### Tasks

Parts of the task:
- [x] Job that runs every second, checks if there is a new block
- [x] Runs the prover, saves the stark proof to the db
- [x] get_header_chain_proof function

### Deadline of the Issue

25/10/2024
