### ISSUE TITLE
Writers for env_writer

### ISSUE THREAD

**Issue by ekrembal** [chainwayxyz/clementine#80]
### Issue Description

Write env_writers for the corresponding guest functions, this way we can add tests that matches writers and readers, and easily make tests for bridge_proof

### Tasks

Parts of the task:
- [ ] write_merkle_tree_proof(leaf: [u8; 32], index: Option<u32>, merkle_tree: MerkleTree)
- [ ] write_blocks(block_headers: Vec<Header>)
- [ ] write_blocks_and_add_to_merkle_tree(block_headers: Vec<Header>, &mut blockhashes_mt: MerkleTree)
